Planetery-Engine: Swapchain
Swapchain
Vulkan Interface
A group of vulkan classes that is related to swapchain. All class in here is provided by default-included SwapchainKHR extension.
Classes
class vk::Swapchain
Swapchain object
class vk::OSRenderSurface
An object repesenting OS-specific surface.
struct vk::OutdatedSwapchainException
A signal that notifies the Swapchain is outdated. The Swapchain should be notified of the event by calling Swapchain::invalidateSwapchain() before throwing this exception.
struct vk::OutdatedFrameException
A signal that notifies the SwapchainImage is outdated.
class vk::SwapchainImage
An image of a Swapcain.
Functions
template<typename LM >
requires std::derived_from<LM, LifetimeManager>
ImageView & vk::SwapchainImage::makeImageView (LM &lm) const
Make an IamgeView using LM as the LifetimeMangager from this image.
Detailed Description
A group of vulkan classes that is related to swapchain. All class in here is provided by default-included SwapchainKHR extension.
Class Documentation
vk::Swapchain
class vk::Swapchain
Swapchain object
An object that holds and manages SwapchainImage. Swapchain may become outdated if the native OSRenderSurface's properties changed, such as window resizing. See OSRenderSurface on how to manage Swapchain lifetime.
Public Member Functions
Swapchain (LogicalDevice &device, OSRenderSurface &surface)
Swapchain (const Swapchain &)=delete
Swapchain (Swapchain &&)=delete
void rebuild () noexcept(false)
Rebuild the Swapchain (blocking)
~Swapchain () final
Destructor (blocking)
SwapchainImage * getNextImage (ulint timeout=ulint(-1)) noexcept(false)
Aquire next SwapchainImage (timed blocking)
bool renderNextImage (ulint timeout=ulint(-1))
Aquire and render next SwapchainImage (timed blocking)
void invalidateAllImages ()
Invalidate all SwapchainImages and reset them (blocking)
void invalidateSwapchain ()
Invalidate the Swapchain and set the 'outdated' flag.
LogicalDevice & getLogicalDevice () const
Get the related LogicalDevice.
OSRenderSurface & getRenderSurface () const
Get the related OSRenderSurface.
MonotonicLifetimeManager & getPerSwapchainResource ()
Get the LifetimeLanager for allocating objects whose lifetime tie to the Swapchain.
uvec2 getPixelSize () const
Get the SwapchainImage pixel size.
bool isValid () const
Check if Swapchain is valid and not outdated.
uint getImageCount () const
Get the count of SwapchainImage.
VkFormat getImageFormat () const
Get the format of SwapchainImage.
LogicalDevice & getDevice () const
Static Public Member Functions
static void setCallback (SwapchainCallback callback)
Set a SwapchainCallback.
static void setCallback (FrameCallback callback)
Set a FrameCallback.
Private Member Functions
void _make () noexcept(false)
Private Attributes
LogicalDevice & d
OSRenderSurface & sf
VkSwapchainKHR sc
VkFormat surfaceFormat
uvec2 pixelSize
bool outdated = false
MonotonicLifetimeManager perSwapchainResource
std::vector< util::OptionalUniquePtr< SwapchainImage > > scImgs {}
std::vector< VkImage > imgs {}
Constructor & Destructor Documentation
Swapchain()
Swapchain::Swapchain (LogicalDevice & device, OSRenderSurface & surface)
Todo:
move this to private
~Swapchain()
Swapchain::~Swapchain () final
Destructor (blocking)
This will first destruct all SwapchainImage, which will block and wait until deallocation and destruction is completed.
Call to SwapchainCallback::onDestroy happens after all SwapchainImage has been destructed.
References vk::LogicalDevice::d.
Member Function Documentation
rebuild()
void Swapchain::rebuild () noexcept
Rebuild the Swapchain (blocking)
This call will rebuild the Swapchain inplace. All SwapchainImage will be destructed even when rebuilds of the Swapchain fails, but not when exception is thrown.
Call to SwapchainCallback::onDestroy happens after the previous Swapchain becomes invalid, and all previous SwapchainImage has been destructed, which will block and wait until deallocation and destruction is completed.
Call to SwapchainCallback::onCreate happens only when the creation of the new Swapchain is successful, and after SwapchainCallback::onDestroy is called.
Exceptions
SurfaceMinimizedException Surface minimized.
Note
Call to SwapchainCallback::onSurfaceMinimized happens before the exception is thrown.
getNextImage()
SwapchainImage * Swapchain::getNextImage (ulint timeout = ulint(-1)) noexcept
Aquire next SwapchainImage (timed blocking)
Try to aquire next SwapchainImage within the provided timeout. If timeout is 0, then this function is non-blocking. May set the outdated flag
Parameters
timeout The maximum nanoseconds the function can wait, or 0 if non-blocking
Returns
A valid SwapchainImage pointer, or nullptr if function fails to aquire the image in time
References vk::LogicalDevice::d.
Referenced by renderNextImage().
renderNextImage()
bool Swapchain::renderNextImage (ulint timeout = ulint(-1))
Aquire and render next SwapchainImage (timed blocking)
Try to aquire next SwapchainImage within the provided timeout. If successful, call the render function. May set the 'outdated' flag
Parameters
timeout The maximum nanoseconds the function can wait when trying to aquire the image, or 0 if non-blocking
Returns
Whether a frame has been rendered successfully
References getNextImage().
invalidateAllImages()
void vk::Swapchain::invalidateAllImages ()
Invalidate all SwapchainImages and reset them (blocking)
Todo:
Add implementation
getDevice()
LogicalDevice & vk::Swapchain::getDevice () const inline
Bug:
Repeated func
Referenced by vk::SwapchainImage::getDevice(), vk::SwapchainImage::makeImageView(), and vk::SwapchainImage::waitForCompletion().
vk::OSRenderSurface
class vk::OSRenderSurface
An object repesenting OS-specific surface.
This is the display-part of a window if in windows mode, or the display if in full screen mode. It contains imformation about the supported display settings
Todo:
Seperate GLFW away from this class
Public Member Functions
OSRenderSurface ()
Make an OSRenderSurface.
OSRenderSurface (const OSRenderSurface &)=delete
OSRenderSurface (OSRenderSurface &&)=delete
~OSRenderSurface ()
Destructor.
Support querySupport (PhysicalDevice &pd)
Query an OSRenderSurface support for this surface. See OSRenderSurface::Support::Support()
Swapchain & querySwapchain (LogicalDevice &device)
Query a Swapchain that is not outdated.
void releaseSwapchain ()
Release and destroy the current Swapchain. (Blocking)
Swapchain * getSwapchain ()
Get the current Swapchain.
Public Attributes
uvec2 preferredImageSize = uvec2(-1)
When making a Swapchain, what the preferred image size is.
uint preferredImageCount = 4
When making a Swapchain, what the preferred image count is.
SurfaceTransparentAction preferredTransparencyAction
When making a Swapchain, what the preferred transparency action is.
Private Attributes
Optional< Swapchain > sc
VkSurfaceKHR surface = nullptr
Constructor & Destructor Documentation
OSRenderSurface()
OSRenderSurface::OSRenderSurface ()
Make an OSRenderSurface.
Todo:
Add callbacks for getting a native surface, and put that to user-side
Member Function Documentation
querySwapchain()
Swapchain & OSRenderSurface::querySwapchain (LogicalDevice & device)
Query a Swapchain that is not outdated.
If the current Swapchain is outdated, Rebuild the Swapchain and return it. If the current Swapchain is not outdated, return it.
Parameters
device What LogicalDevice the Swapchain should be built on
Exceptions
SurfaceMinimizedException If the current Swapchain is outdated, and on rebuilding the Swapchain, the OSRenderSurface is detected to be minimized, this exception will be thrown to signal that the Surface had been minimized when it is rebuilding the Swapchain, in which the Swapchain will be set to be outdated.
Call to SwapchainCallback::onSurfaceMinimized happens before the exception is thrown.
getSwapchain()
Swapchain * vk::OSRenderSurface::getSwapchain () inline
Get the current Swapchain.
It returns the Swapchain directly, and does not update/remake the Swapchain.
Returns
A pointer to the surface's valid Swapchain, or nullptr if a Swapchain does not exist yet.
Member Data Documentation
preferredTransparencyAction
SurfaceTransparentAction vk::OSRenderSurface::preferredTransparencyAction
Initial value:
=
          SurfaceTransparentAction::RemoveAlpha
When making a Swapchain, what the preferred transparency action is.
vk::OutdatedSwapchainException
struct vk::OutdatedSwapchainException
A signal that notifies the Swapchain is outdated. The Swapchain should be notified of the event by calling Swapchain::invalidateSwapchain() before throwing this exception.
vk::OutdatedFrameException
struct vk::OutdatedFrameException
A signal that notifies the SwapchainImage is outdated.
Todo:
Add the functionality for invalidating a SwpachainImage
vk::SwapchainImage
class vk::SwapchainImage
An image of a Swapcain.
Public Member Functions
SwapchainImage (Swapchain &sc, uint imgId, VkImage img, Semaphore &&sp)
SwapchainImage (const SwapchainImage &)=delete
SwapchainImage (SwapchainImage &&)=delete
bool waitForCompletion (ulint timeout=-1) const
Wait until the frame can be cleanup within the timeout.
void invalidateImage ()
Invalidate the image, to trigger a reset.
ImageView makeImageView () const
Make an ImageView from this image.
template<typename LM >
requires std::derived_from<LM, LifetimeManager>
ImageView & makeImageView (LM &lm) const
Make an IamgeView using LM as the LifetimeMangager from this image.
bool hasAquiredImage () const
Check if it has aquired the image back yet.
Swapchain & getSwapchain () const
Get the underlying Swapchain.
LogicalDevice & getDevice () const
Get the underlying LogicalDevice.
Semaphore & getImageRecievedSemaphore () const
Get the Semaphore that will be signaled when the image is recieved and is usable.
MonotonicLifetimeManager & getPerFrameResource ()
Get the Per-Frame LifetimeManager, which resets per frame.
MonotonicLifetimeManager & getPerImageResource ()
Get the Per-Image LifetimeManager, which resets when the SwapchainImage resets.
VkFormat getFormat () const
Get the format of the SwapchainImage.
uint getImageIndex () const
Get the SwapchainImage index for its underlying Swapchain.
VkImageViewCreateInfo _getImgViewInfo () const
Internal use.
Private Member Functions
void setImageAquired (Semaphore &&sp)
Private Attributes
Variant< Semaphore *, Fence * > imgAquireSpOrCompleteFc
uint imgId
VkImage img
Swapchain & sc
MonotonicLifetimeManager perFrameResource {}
MonotonicLifetimeManager perImageResource {}
Constructor & Destructor Documentation
SwapchainImage()
SwapchainImage::SwapchainImage (Swapchain & sc, uint imgId, VkImage img, Semaphore && sp)
Todo:
Move to private, call by Swapchain
Member Function Documentation
waitForCompletion()
bool SwapchainImage::waitForCompletion (ulint timeout = -1) const
Wait until the frame can be cleanup within the timeout.
If it timeout from waiting, return false. If the frame hasn't been sent, return false immidiatly.
References vk::LogicalDevice::d, and vk::Swapchain::getDevice().
invalidateImage()
void vk::SwapchainImage::invalidateImage ()
Invalidate the image, to trigger a reset.
Todo:
Add this
_getImgViewInfo()
VkImageViewCreateInfo vk::SwapchainImage::_getImgViewInfo () const
Internal use.
Todo:
move to private
Referenced by makeImageView().