Planetery-Engine: Queue
Queue
Vulkan Interface
A group of vulkan classes that is related to device queue. See also LogicalDevice.
Classes
struct vk::QueueHint
Hint struct for queues usage.
class vk::QueuePoolLayout
QueuePool layout.
class vk::QueuePool
Queue pool.
class vk::Queue
A queue object for submiting commends.
Enumerations
enum vk::HintUsage { vk::Memory , vk::Present , vk::Present = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR , vk::Render }
Hint enum.
Detailed Description
A group of vulkan classes that is related to device queue. See also LogicalDevice.
Class Documentation
vk::QueueHint
struct vk::QueueHint
Hint struct for queues usage.
Class Members
uint memoryIndex
uint presentIndex
uint renderIndex
vk::QueuePoolLayout
class vk::QueuePoolLayout
QueuePool layout.
A layout object for setting up the desired QueuePool layout. On construction, this loads the constraint of the layout, which then can be queried via its const function. Call the non-const function to setup the desire layout. This object should then be provided to LogicalDevice::LogicalDeivce(PhysicalDeivce&, const QueuePoolLayout&) ctor. The LogicalDevice will then construct a QueuePool following this QueuePoolLayout.
Public Member Functions
QueuePoolLayout (const PhysicalDevice &pd)
Construct a QueuePool layout constrainted to the physical device.
Flags< QueueType > getFamilySupportType (uint familyIndex) const
Get the allowed queue operations of a queue family.
uint getFamilyMaxQueueCount (uint familyIndex) const
Get the max allowed queue count of a queue family.
uint findFamilyBySupportType (Flags< QueueType > mustSupport, Flags< QueueType > mustNotSupport=Flags< QueueType >()) const
Find a queue family filtered by its allowed queue operations.
bool checkQueuePresentSupport (uint familyIndex, const OSRenderSurface &surface) const
Check if a queue family supports presenting a SwapchainImage to the specified OSRenderSurface.
void addQueueGroup (uint familyIndex, uint count)
Add a queue group to the layout.
void hintGroupUsage (HintUsage usage, uint familyIndex)
Provide a hint for how to use a group.
Private Member Functions
std::vector< VkDeviceQueueCreateInfo > getQueueCreateInfos () const
Private Attributes
std::vector< std::pair< uint, uint > > queueGroups {}
std::vector< FamilySupport > queueFamilyProperties {}
QueueHint hint
VkPhysicalDevice pd
Constructor & Destructor Documentation
QueuePoolLayout()
QueuePoolLayout::QueuePoolLayout (const PhysicalDevice & pd)
Construct a QueuePool layout constrainted to the physical device.
Parameters
pd A physical device that the layout should be compatible with
Note
There are no futher access to pd after the constructer returns
References vk::Compute, vk::PhysicalDevice::d, vk::Graphics, and vk::MemoryTransfer.
Member Function Documentation
getFamilySupportType()
Flags< QueueType > QueuePoolLayout::getFamilySupportType (uint familyIndex) const
Get the allowed queue operations of a queue family.
Parameters
familyIndex The queue family index
Returns
The allowed queue opertions
getFamilyMaxQueueCount()
uint vk::QueuePoolLayout::getFamilyMaxQueueCount (uint familyIndex) const
Get the max allowed queue count of a queue family.
Parameters
familyIndex The queue family index
Returns
The max allowed queue count
findFamilyBySupportType()
uint QueuePoolLayout::findFamilyBySupportType (Flags< QueueType > mustSupport, Flags< QueueType > mustNotSupport = Flags<QueueType>()) const
Find a queue family filtered by its allowed queue operations.
Parameters
mustSupport The queue operations it must support
mustNotSupport The queue operations it must not support
Returns
The queue family index
Todo:
This will be changed to use Iteratiors or Ranges for better filtering
Referenced by vk::PhysicalDevice::PhysicalDevice().
checkQueuePresentSupport()
bool vk::QueuePoolLayout::checkQueuePresentSupport (uint familyIndex, const OSRenderSurface & surface) const
Check if a queue family supports presenting a SwapchainImage to the specified OSRenderSurface.
Parameters
familyIndex The queue family index
surface The surface to check against
Returns
A boolean where true means it supports the surface
addQueueGroup()
void QueuePoolLayout::addQueueGroup (uint familyIndex, uint count)
Add a queue group to the layout.
Parameters
familyIndex The family index that the queue group should use
count The max queue count of the queue group
Warning
The family index must be unique currently as each queue families must only be linked to at most one queue group.
Todo:
This behaviour may change later.
hintGroupUsage()
void vk::QueuePoolLayout::hintGroupUsage (HintUsage usage, uint familyIndex)
Provide a hint for how to use a group.
Parameters
usage The hinted usage
familyIndex The group's familyIndex
References vk::Memory, vk::Present, and vk::Render.
vk::QueuePool
class vk::QueuePool
Queue pool.
An object owned by a LogicalDevice. It manages the lifetime and usages of Queues.
Warning
This object should NEVER be constructed manually. Instead, this object is automatically constructed when constructing a LogicalDevice.
In-Use queues mean a queue that have been queried before using queryQueueNotInUse(), and that have yet called markQueueNotUnUse().
Todo:
Fix the In-Use queue machanic
Public Member Functions
QueuePool (const QueuePoolLayout &layout, LogicalDevice &device)
~QueuePool ()=default
Destructer.
uint findGroupBySupportType (Flags< QueueType > mustSupport, Flags< QueueType > mustNotSupport=Flags< QueueType >()) const
Find a queue group filtered by its allowed queue operations.
Queue * queryQueueInUse (uint groupId)
Query a Queue object that is in-use.
Queue * queryQueueNotInUse (uint groupId)
Query a Queue object that is not in-use.
void markQueueNotInUse (Queue &queue)
Mark a Queue object as not in-use.
uint getGroupByHint (HintUsage usage) const
Get a Queue group using the hint provided when setting up the QueuePoolLayout.
LogicalDevice & getDevice () const
Get the related LogicalDevice.
CommendPool & queryCommendPool (uint groupId, Flags< CommendPoolType > type)
Query a CommendPool for a Queue group.
Queue & getExpressMemoryCopyQueue ()
Get an express queue for Memory copy operations.
Queue & getExpressRenderQueue ()
Get an express queue for Render operations.
Private Attributes
LogicalDevice & d
std::unordered_map< uint, Group > groups {}
QueueHint hint
Constructor & Destructor Documentation
QueuePool()
QueuePool::QueuePool (const QueuePoolLayout & layout, LogicalDevice & device)
Todo:
Move this to private
Member Function Documentation
findGroupBySupportType()
uint QueuePool::findGroupBySupportType (Flags< QueueType > mustSupport, Flags< QueueType > mustNotSupport = Flags<QueueType>()) const
Find a queue group filtered by its allowed queue operations.
Parameters
mustSupport The queue operations it must support
mustNotSupport The queue operations it must not support
Returns
The queue family index of the group
Todo:
This will be changed to use Iteratiors or Ranges for better filtering
queryQueueInUse()
Queue * QueuePool::queryQueueInUse (uint groupId)
Query a Queue object that is in-use.
Parameters
groupId The group index
Returns
A valid queue pointer, or nullptr if no queue is in use
queryQueueNotInUse()
Queue * QueuePool::queryQueueNotInUse (uint groupId)
Query a Queue object that is not in-use.
Parameters
groupId The group index
Returns
A valid queue pointer, or nullptr if no queue is in use
Note
Concider calling markQueueNotInUse() when the queue is not needed anymore. This is only a suggestion as the vkInUseQueue in-use thing is not really fully functional.
markQueueNotInUse()
void vk::QueuePool::markQueueNotInUse (Queue & queue)
Mark a Queue object as not in-use.
Parameters
queue The target Queue object
References vk::Queue::familyIndex, vk::Queue::getQueuePool(), and vk::Queue::queueIndex.
getGroupByHint()
uint QueuePool::getGroupByHint (HintUsage usage) const
Get a Queue group using the hint provided when setting up the QueuePoolLayout.
Parameters
usage The type of usage
Returns
The Queue group index, or uint(-1) if the hint of the usage is not set
Note
This is faster than using findGroupBySupportType() as it uses constant time, independant of how many groups there are.
References vk::Memory, vk::Present, and vk::Render.
queryCommendPool()
CommendPool & QueuePool::queryCommendPool (uint groupId, Flags< CommendPoolType > type)
Query a CommendPool for a Queue group.
Query a CommendPool that is compatible with the queue group. If one with the same CommendPoolType and in the same queue group is not present, it will make a new one.
Parameters
groupId The queue group it sould be compatible to
type The CommendPool type
Returns
A CommendPool
Note
The queried CommendPool's CommendBuffer should be submitable, and only submitable to a Queue in the targeted queue group. See also Queue::Submit()
getExpressMemoryCopyQueue()
Queue & vk::QueuePool::getExpressMemoryCopyQueue ()
Get an express queue for Memory copy operations.
Todo:
Actually add priority for queues
References vk::Memory, and vk::MemoryTransfer.
getExpressRenderQueue()
Queue & vk::QueuePool::getExpressRenderQueue ()
Get an express queue for Render operations.
Todo:
Actually add priority for queues
References vk::Graphics, and vk::Render.
vk::Queue
class vk::Queue
A queue object for submiting commends.
This repesent a queue for the underlying LogicalDevice. It recieves commends via collecting CommendBuffer. See Queue::submit()
This should only be constructed via QueuePool::query*() function.
Public Member Functions
Queue (QueuePool &queuePool, uint familyIndex, uint queueIndex)
Queue (const Queue &)=delete
Queue (Queue &&)=delete
~Queue () final=default
Queue destructor Its underlying object's lifetime is linked to LogicalDevice and therefore no special destructor is needed.
LogicalDevice & getDevice ()
Get the underlying LogicalDevice.
QueuePool & getQueuePool ()
Get the QueuePool that the Queue is in.
void submit (CommendBuffer &cb, Semaphore *waitFor, PipelineStage waitType, Semaphore *signalToSemaphore, Fence *signalToFence)
Submit a CommendBuffer for execution.
void presentImage (SwapchainImage &scImg, Semaphore &presentSemaphore, Fence &cleanupFence)
Presents a SwapchainImage to the Swapchain.
Public Attributes
const uint familyIndex
Read-only value of the Queue's family index.
const uint queueIndex
Read-only value of the Queue index in a group.
Private Attributes
QueuePool & qp
VkQueue q
Constructor & Destructor Documentation
Queue()
Queue::Queue (QueuePool & queuePool, uint familyIndex, uint queueIndex)
Todo:
move to private
References vk::LogicalDevice::d, and vk::QueuePool::getDevice().
Member Function Documentation
submit()
void vk::Queue::submit (CommendBuffer & cb, Semaphore * waitFor, PipelineStage waitType, Semaphore * signalToSemaphore, Fence * signalToFence)
Submit a CommendBuffer for execution.
The queue collects CommendBuffer to a multithread-safe queue, and after an undetermined delay, will start executing the CommendBuffers' commend in order and in parrellal.
Parameters
cb The commend buffer to submit
waitFor For cross queue syncing.
What Semaphore object to wait for, or nullptr if no waiting is needed
waitType For same queue syncing.
What PipelineStage of the previous commend to wait for
signalToSemaphore For cross queue syncing.
What Semaphore object to signal to, or nullptr if no signaling is needed
signalToFence For syncing to user process.
What Fence object to signal to, or nullptr if no signaling is needed
Warning
While CommendBuffer is executed in order, CommendBuffers dependent on each other submitted to the same queue still requires syncing via pipeline barriers or execution barriers as multiple commends (even across CommendBuffer).
CommendBuffers dependent on each other submitted to different queues requires syncing via synchronization object. (see Sync)
Todo:
Add back multi-commend submitions in a single commend
Todo:
Add back TimelineSemaphore support
presentImage()
void Queue::presentImage (SwapchainImage & scImg, Semaphore & presentSemaphore, Fence & cleanupFence)
Presents a SwapchainImage to the Swapchain.
This presents a previously aquired SwapchainImage to the Swapchain. The execution order obeys the same rule as normal CommendBuffer submit(), except that it must be synchronized using Semaphore
Parameters
scImg The target SwapchainImage
presentSemaphore The Semaphore to wait for presentation
cleanupFence The Fence that is signaled when all previous commends that uses the Swapchain's LifetimeManager's allocated object has completed, and that cleanups can be called
Exceptions
OutdatedSwapchainException Signal that Swapchain is outdated when trying to present the image
References vk::Swapchain::invalidateSwapchain().
Enumeration Type Documentation
HintUsage
enum vk::HintUsage
Hint enum.
Enumerator
Memory
Memory Copy Operations.
Present
Presentation Operations.
Present
Prsentation to an OSRnderSurface.
Note
Provided by VK_KHR_swapchain
Render
Render Operations.