var annotated_dup =
[
    [ "events", null, [
      [ "KeyModFlags", "classevents_1_1KeyModFlags.html", null ],
      [ "ThreadEvents", "classevents_1_1ThreadEvents.html", null ]
    ] ],
    [ "font", null, [
      [ "Data", "structfont_1_1Data.html", null ],
      [ "FontFace", "classfont_1_1FontFace.html", null ],
      [ "FontFaceData", "structfont_1_1FontFaceData.html", null ],
      [ "FontSet", "classfont_1_1FontSet.html", null ],
      [ "GlyphData", "structfont_1_1GlyphData.html", null ],
      [ "Reader", "classfont_1_1Reader.html", null ],
      [ "RenderData", "structfont_1_1RenderData.html", null ]
    ] ],
    [ "gl", null, [
      [ "Base", "classgl_1_1Base.html", null ],
      [ "BufferBase", "classgl_1_1BufferBase.html", null ],
      [ "FrameBuffer", "classgl_1_1FrameBuffer.html", null ],
      [ "GLRect", "structgl_1_1GLRect.html", null ],
      [ "IndiceBuffer", "classgl_1_1IndiceBuffer.html", null ],
      [ "RenderBuffer", "classgl_1_1RenderBuffer.html", null ],
      [ "RenderTarget", "classgl_1_1RenderTarget.html", null ],
      [ "Shader", "classgl_1_1Shader.html", null ],
      [ "ShaderProgram", "classgl_1_1ShaderProgram.html", null ],
      [ "ShaderStorageBuffer", "classgl_1_1ShaderStorageBuffer.html", null ],
      [ "Texture", "classgl_1_1Texture.html", null ],
      [ "Texture2D", "classgl_1_1Texture2D.html", null ],
      [ "VertexAttributeArray", "classgl_1_1VertexAttributeArray.html", null ],
      [ "VertexBuffer", "classgl_1_1VertexBuffer.html", null ]
    ] ],
    [ "Logger", null, [
      [ "LogLayerBase", "classLogger_1_1LogLayerBase.html", null ],
      [ "LogLayerContainer", "classLogger_1_1LogLayerContainer.html", null ],
      [ "LogLayerString", "classLogger_1_1LogLayerString.html", null ],
      [ "Message", "classLogger_1_1Message.html", null ],
      [ "SingleThread", "classLogger_1_1SingleThread.html", null ]
    ] ],
    [ "pmr", null, [
      [ "Allocator", "classpmr_1_1Allocator.html", null ],
      [ "BadAllocException", "structpmr_1_1BadAllocException.html", null ],
      [ "BadArgException", "structpmr_1_1BadArgException.html", null ],
      [ "BadDeallocException", "structpmr_1_1BadDeallocException.html", null ],
      [ "CorruptedMemoryException", "structpmr_1_1CorruptedMemoryException.html", null ],
      [ "StackMemoryResource", "classpmr_1_1StackMemoryResource.html", null ]
    ] ],
    [ "render", null, [
      [ "RenderHandle", "structrender_1_1RenderHandle.html", null ],
      [ "ThreadRender", "classrender_1_1ThreadRender.html", null ]
    ] ],
    [ "sync", null, [
      [ "Promisee", "classsync_1_1Promisee.html", null ],
      [ "Promisee< bool >", "classsync_1_1Promisee_3_01bool_01_4.html", null ],
      [ "Promisor", "classsync_1_1Promisor.html", null ],
      [ "Promisor< bool >", "classsync_1_1Promisor_3_01bool_01_4.html", null ]
    ] ],
    [ "utf", null, [
      [ "UTFIterator", "classutf_1_1UTFIterator.html", null ]
    ] ],
    [ "util", null, [
      [ "DeferredCtor", "classutil_1_1DeferredCtor.html", null ],
      [ "ManualLifetime", "classutil_1_1ManualLifetime.html", null ],
      [ "MBRPool", "classutil_1_1MBRPool.html", null ],
      [ "OptionalUnique", "classutil_1_1OptionalUnique.html", null ],
      [ "OptionalUniquePtr", "classutil_1_1OptionalUniquePtr.html", null ],
      [ "PMRPair", "classutil_1_1PMRPair.html", null ],
      [ "RepeatIterator", "classutil_1_1RepeatIterator.html", null ],
      [ "Timer", "classutil_1_1Timer.html", null ],
      [ "Trap", "classutil_1_1Trap.html", null ],
      [ "Trap< P >", "classutil_1_1Trap_3_01P_01_4.html", null ],
      [ "ValPtrUnion", "classutil_1_1ValPtrUnion.html", null ]
    ] ],
    [ "vk", "namespacevk.html", [
      [ "Buffer", "classvk_1_1Buffer.html", "classvk_1_1Buffer" ],
      [ "CommendBuffer", "classvk_1_1CommendBuffer.html", null ],
      [ "CommendPool", "classvk_1_1CommendPool.html", null ],
      [ "ComplexObject", "structvk_1_1ComplexObject.html", null ],
      [ "DescriptorContainer", "classvk_1_1DescriptorContainer.html", null ],
      [ "DescriptorLayout", "classvk_1_1DescriptorLayout.html", "classvk_1_1DescriptorLayout" ],
      [ "DescriptorLayoutBinding", "namespacevk.html#structvk_1_1DescriptorLayoutBinding", null ],
      [ "DescriptorPool", "classvk_1_1DescriptorPool.html", null ],
      [ "DescriptorSet", "classvk_1_1DescriptorSet.html", "classvk_1_1DescriptorSet" ],
      [ "DeviceCallback", "structvk_1_1DeviceCallback.html", null ],
      [ "DeviceMemory", "structvk_1_1DeviceMemory.html", null ],
      [ "Extension", "group__vkDevice.html#structvk_1_1Extension", null ],
      [ "Fence", "classvk_1_1Fence.html", null ],
      [ "FrameBuffer", "classvk_1_1FrameBuffer.html", null ],
      [ "FrameCallback", "structvk_1_1FrameCallback.html", null ],
      [ "HeapLifetimeManager", "classvk_1_1HeapLifetimeManager.html", null ],
      [ "Image", "classvk_1_1Image.html", null ],
      [ "ImageSampler", "classvk_1_1ImageSampler.html", null ],
      [ "ImageView", "classvk_1_1ImageView.html", null ],
      [ "IndexBuffer", "classvk_1_1IndexBuffer.html", null ],
      [ "Layer", "group__vkDevice.html#structvk_1_1Layer", null ],
      [ "LifetimeManager", "classvk_1_1LifetimeManager.html", null ],
      [ "LogicalDevice", "classvk_1_1LogicalDevice.html", null ],
      [ "MemoryAllocator", "classvk_1_1MemoryAllocator.html", null ],
      [ "MemoryPointer", "namespacevk.html#structvk_1_1MemoryPointer", null ],
      [ "MemoryPool", "classvk_1_1MemoryPool.html", "classvk_1_1MemoryPool" ],
      [ "MonotonicLifetimeManager", "classvk_1_1MonotonicLifetimeManager.html", null ],
      [ "OSRenderSurface", "classvk_1_1OSRenderSurface.html", "classvk_1_1OSRenderSurface" ],
      [ "OutdatedFrameException", "namespacevk.html#structvk_1_1OutdatedFrameException", null ],
      [ "OutdatedSwapchainException", "namespacevk.html#structvk_1_1OutdatedSwapchainException", null ],
      [ "PhysicalDevice", "classvk_1_1PhysicalDevice.html", null ],
      [ "Queue", "classvk_1_1Queue.html", null ],
      [ "QueueHint", "namespacevk.html#structvk_1_1QueueHint", null ],
      [ "QueuePool", "classvk_1_1QueuePool.html", "classvk_1_1QueuePool" ],
      [ "QueuePoolLayout", "classvk_1_1QueuePoolLayout.html", "classvk_1_1QueuePoolLayout" ],
      [ "RenderPass", "classvk_1_1RenderPass.html", "classvk_1_1RenderPass" ],
      [ "RenderPipeline", "classvk_1_1RenderPipeline.html", "classvk_1_1RenderPipeline" ],
      [ "Semaphore", "classvk_1_1Semaphore.html", null ],
      [ "ShaderCompiled", "classvk_1_1ShaderCompiled.html", null ],
      [ "StorageBuffer", "classvk_1_1StorageBuffer.html", null ],
      [ "SurfaceMinimizedException", "group__vkDevice.html#structvk_1_1SurfaceMinimizedException", null ],
      [ "Swapchain", "classvk_1_1Swapchain.html", null ],
      [ "SwapchainCallback", "structvk_1_1SwapchainCallback.html", null ],
      [ "SwapchainImage", "classvk_1_1SwapchainImage.html", null ],
      [ "SyncLine", "structvk_1_1SyncLine.html", null ],
      [ "SyncPoint", "structvk_1_1SyncPoint.html", null ],
      [ "TextureSubLayers", "namespacevk.html#structvk_1_1TextureSubLayers", null ],
      [ "TextureSubRegion", "namespacevk.html#structvk_1_1TextureSubRegion", null ],
      [ "TimelineSemaphore", "classvk_1_1TimelineSemaphore.html", null ],
      [ "UniformBuffer", "classvk_1_1UniformBuffer.html", null ],
      [ "VertexAttribute", "classvk_1_1VertexAttribute.html", null ],
      [ "VertexBuffer", "classvk_1_1VertexBuffer.html", null ]
    ] ],
    [ "_Glyph", "struct__Glyph.html", null ],
    [ "_KeyCallback", "struct__KeyCallback.html", null ],
    [ "_KeyEvent", "struct__KeyEvent.html", null ],
    [ "_state", "struct__state.html", null ],
    [ "_Thread", "struct__Thread.html", null ],
    [ "_WindowCallback", "struct__WindowCallback.html", null ],
    [ "CharFlags", "structCharFlags.html", null ],
    [ "ConvertedIterator", "classConvertedIterator.html", null ],
    [ "CView", "classCView.html", null ],
    [ "Flags", "classFlags.html", null ],
    [ "Flags< BufferUseType >", "group__vkBufferEnum.html#classFlags_3_01BufferUseType_01_4", null ],
    [ "Flags< ColorComponents >", "group__vkPipelineEnum.html#classFlags_3_01ColorComponents_01_4", null ],
    [ "Flags< CommendBufferUsage >", "group__vkCommendEnum.html#classFlags_3_01CommendBufferUsage_01_4", null ],
    [ "Flags< CommendPoolType >", "group__vkCommendEnum.html#classFlags_3_01CommendPoolType_01_4", null ],
    [ "Flags< CullMode >", "group__vkPipelineEnum.html#classFlags_3_01CullMode_01_4", null ],
    [ "Flags< DescriptorPoolType >", "group__vkDescriptorEnum.html#classFlags_3_01DescriptorPoolType_01_4", null ],
    [ "Flags< ImageUseType >", "group__vkImageEnum.html#classFlags_3_01ImageUseType_01_4", null ],
    [ "Flags< MemoryAccess >", "group__vkMemoryEnum.html#classFlags_3_01MemoryAccess_01_4", null ],
    [ "Flags< MemoryFeature >", "group__vkMemoryEnum.html#classFlags_3_01MemoryFeature_01_4", null ],
    [ "Flags< PipelineStage >", "group__vkPipelineEnum.html#classFlags_3_01PipelineStage_01_4", null ],
    [ "Flags< QueueType >", "group__vkQueueEnum.html#classFlags_3_01QueueType_01_4", null ],
    [ "Flags< SampleCount >", "group__vkImageEnum.html#classFlags_3_01SampleCount_01_4", null ],
    [ "Flags< ShaderType >", "group__vkShaderEnum.html#classFlags_3_01ShaderType_01_4", null ],
    [ "Flags< TextureAspect >", "group__vkImageEnum.html#classFlags_3_01TextureAspect_01_4", null ],
    [ "Flags< TextureFeature >", "group__vkImageEnum.html#classFlags_3_01TextureFeature_01_4", null ],
    [ "ImageContainer", "structImageContainer.html", null ],
    [ "iterator_return", "structiterator__return.html", null ],
    [ "Log", "classLog.html", null ],
    [ "MemoryResource", "classMemoryResource.html", null ],
    [ "MultiCharState", "structMultiCharState.html", null ],
    [ "MultilineString", "classMultilineString.html", null ],
    [ "MultiStream", "classMultiStream.html", "classMultiStream" ],
    [ "RollingAverage", "classRollingAverage.html", null ],
    [ "StringBox", "classStringBox.html", null ],
    [ "Swapper", "classSwapper.html", null ],
    [ "View", "classView.html", null ],
    [ "VkAttachmentDescription", "classVkAttachmentDescription.html", null ],
    [ "VkPipelineColorBlendAttachmentState", "classVkPipelineColorBlendAttachmentState.html", null ],
    [ "VkPipelineDepthStencilStateCreateInfo", "classVkPipelineDepthStencilStateCreateInfo.html", null ],
    [ "VkPipelineShaderStageCreateInfo", "classVkPipelineShaderStageCreateInfo.html", null ],
    [ "VkPushConstantRange", "classVkPushConstantRange.html", null ],
    [ "VkSubpassDependency", "classVkSubpassDependency.html", null ]
];