var annotated_dup =
[
    [ "events", null, [
      [ "KeyModFlags", "d5/dc2/classevents_1_1KeyModFlags.html", null ],
      [ "ThreadEvents", "d0/dc0/classevents_1_1ThreadEvents.html", null ]
    ] ],
    [ "font", null, [
      [ "Data", "dd/d15/structfont_1_1Data.html", null ],
      [ "FontFace", "d5/db7/classfont_1_1FontFace.html", null ],
      [ "FontFaceData", "da/dc6/structfont_1_1FontFaceData.html", null ],
      [ "FontSet", "db/d32/classfont_1_1FontSet.html", null ],
      [ "GlyphData", "d7/d9f/structfont_1_1GlyphData.html", null ],
      [ "Reader", "dc/d0d/classfont_1_1Reader.html", null ],
      [ "RenderData", "de/d74/structfont_1_1RenderData.html", null ]
    ] ],
    [ "gl", null, [
      [ "Base", "d7/d01/classgl_1_1Base.html", null ],
      [ "BufferBase", "d7/d59/classgl_1_1BufferBase.html", null ],
      [ "FrameBuffer", "d1/dd1/classgl_1_1FrameBuffer.html", null ],
      [ "GLRect", "de/d8f/structgl_1_1GLRect.html", null ],
      [ "IndiceBuffer", "de/d2d/classgl_1_1IndiceBuffer.html", null ],
      [ "RenderBuffer", "d7/ddf/classgl_1_1RenderBuffer.html", null ],
      [ "RenderTarget", "db/df6/classgl_1_1RenderTarget.html", null ],
      [ "Shader", "dd/dd9/classgl_1_1Shader.html", null ],
      [ "ShaderProgram", "dc/dd8/classgl_1_1ShaderProgram.html", null ],
      [ "ShaderStorageBuffer", "db/d01/classgl_1_1ShaderStorageBuffer.html", null ],
      [ "Texture", "de/de9/classgl_1_1Texture.html", null ],
      [ "Texture2D", "d1/d9c/classgl_1_1Texture2D.html", null ],
      [ "VertexAttributeArray", "de/d4e/classgl_1_1VertexAttributeArray.html", null ],
      [ "VertexBuffer", "d4/df2/classgl_1_1VertexBuffer.html", null ]
    ] ],
    [ "Logger", null, [
      [ "LogLayerBase", "da/dfd/classLogger_1_1LogLayerBase.html", null ],
      [ "LogLayerContainer", "d0/dea/classLogger_1_1LogLayerContainer.html", null ],
      [ "LogLayerString", "d8/d66/classLogger_1_1LogLayerString.html", null ],
      [ "Message", "d0/dd3/classLogger_1_1Message.html", null ],
      [ "SingleThread", "d1/d3c/classLogger_1_1SingleThread.html", null ]
    ] ],
    [ "pmr", null, [
      [ "Allocator", "d7/d02/classpmr_1_1Allocator.html", null ],
      [ "BadAllocException", "d6/dea/structpmr_1_1BadAllocException.html", null ],
      [ "BadArgException", "db/daf/structpmr_1_1BadArgException.html", null ],
      [ "BadDeallocException", "d4/d63/structpmr_1_1BadDeallocException.html", null ],
      [ "CorruptedMemoryException", "db/dbe/structpmr_1_1CorruptedMemoryException.html", null ],
      [ "StackMemoryResource", "d7/d94/classpmr_1_1StackMemoryResource.html", null ]
    ] ],
    [ "render", null, [
      [ "RenderHandle", "de/d34/structrender_1_1RenderHandle.html", null ],
      [ "ThreadRender", "d3/d92/classrender_1_1ThreadRender.html", null ]
    ] ],
    [ "sync", null, [
      [ "Promisee", "d1/de3/classsync_1_1Promisee.html", null ],
      [ "Promisee< bool >", "d9/d94/classsync_1_1Promisee_3_01bool_01_4.html", null ],
      [ "Promisor", "dd/d1c/classsync_1_1Promisor.html", null ],
      [ "Promisor< bool >", "d3/d47/classsync_1_1Promisor_3_01bool_01_4.html", null ]
    ] ],
    [ "utf", null, [
      [ "UTFIterator", "de/d1d/classutf_1_1UTFIterator.html", null ]
    ] ],
    [ "util", null, [
      [ "DeferredCtor", "d4/d6c/classutil_1_1DeferredCtor.html", null ],
      [ "ManualLifetime", "d7/d28/classutil_1_1ManualLifetime.html", null ],
      [ "MBRPool", "df/d64/classutil_1_1MBRPool.html", null ],
      [ "OptionalUnique", "d0/d7f/classutil_1_1OptionalUnique.html", null ],
      [ "OptionalUniquePtr", "d4/db4/classutil_1_1OptionalUniquePtr.html", null ],
      [ "PMRPair", "d0/dea/classutil_1_1PMRPair.html", null ],
      [ "RepeatIterator", "d7/d4b/classutil_1_1RepeatIterator.html", null ],
      [ "Timer", "d1/d2f/classutil_1_1Timer.html", null ],
      [ "Trap", "d4/d5e/classutil_1_1Trap.html", null ],
      [ "Trap< P >", "d5/def/classutil_1_1Trap_3_01P_01_4.html", null ],
      [ "ValPtrUnion", "d6/d17/classutil_1_1ValPtrUnion.html", null ]
    ] ],
    [ "vk", "d5/df6/namespacevk.html", [
      [ "Buffer", "dd/dda/classvk_1_1Buffer.html", "dd/dda/classvk_1_1Buffer" ],
      [ "CommendBuffer", "dc/d2b/classvk_1_1CommendBuffer.html", null ],
      [ "CommendPool", "d4/d31/classvk_1_1CommendPool.html", null ],
      [ "ComplexObject", "d5/db0/structvk_1_1ComplexObject.html", null ],
      [ "DescriptorContainer", "d3/dea/classvk_1_1DescriptorContainer.html", null ],
      [ "DescriptorLayout", "d0/d39/classvk_1_1DescriptorLayout.html", "d0/d39/classvk_1_1DescriptorLayout" ],
      [ "DescriptorLayoutBinding", "d5/df6/namespacevk.html#d5/d0f/structvk_1_1DescriptorLayoutBinding", null ],
      [ "DescriptorPool", "de/d06/classvk_1_1DescriptorPool.html", null ],
      [ "DescriptorSet", "d4/dba/classvk_1_1DescriptorSet.html", "d4/dba/classvk_1_1DescriptorSet" ],
      [ "DeviceCallback", "d9/d48/structvk_1_1DeviceCallback.html", null ],
      [ "DeviceMemory", "dc/d50/structvk_1_1DeviceMemory.html", null ],
      [ "Extension", "d1/d93/group__vkDevice.html#d5/d21/structvk_1_1Extension", null ],
      [ "Fence", "d2/d45/classvk_1_1Fence.html", null ],
      [ "FrameBuffer", "df/d40/classvk_1_1FrameBuffer.html", null ],
      [ "FrameCallback", "db/dda/structvk_1_1FrameCallback.html", null ],
      [ "HeapLifetimeManager", "d1/d5a/classvk_1_1HeapLifetimeManager.html", null ],
      [ "Image", "de/dfe/classvk_1_1Image.html", null ],
      [ "ImageSampler", "d1/d76/classvk_1_1ImageSampler.html", null ],
      [ "ImageView", "d6/db3/classvk_1_1ImageView.html", null ],
      [ "IndexBuffer", "dd/d96/classvk_1_1IndexBuffer.html", null ],
      [ "Layer", "d1/d93/group__vkDevice.html#d6/d4d/structvk_1_1Layer", null ],
      [ "LifetimeManager", "dd/d97/classvk_1_1LifetimeManager.html", null ],
      [ "LogicalDevice", "d1/d93/group__vkDevice.html#d6/d4f/classvk_1_1LogicalDevice", "d1/d93/group__vkDevice_d6/d4f/classvk_1_1LogicalDevice" ],
      [ "MemoryAllocator", "d7/d01/classvk_1_1MemoryAllocator.html", null ],
      [ "MemoryPointer", "d5/df6/namespacevk.html#d7/de4/structvk_1_1MemoryPointer", null ],
      [ "MemoryPool", "d7/da4/classvk_1_1MemoryPool.html", "d7/da4/classvk_1_1MemoryPool" ],
      [ "MonotonicLifetimeManager", "dc/d5b/classvk_1_1MonotonicLifetimeManager.html", null ],
      [ "OSRenderSurface", "d1/d3e/group__vkSwapchain.html#d8/d35/classvk_1_1OSRenderSurface", "d1/d3e/group__vkSwapchain_d8/d35/classvk_1_1OSRenderSurface" ],
      [ "OutdatedFrameException", "d1/d3e/group__vkSwapchain.html#db/df7/structvk_1_1OutdatedFrameException", null ],
      [ "OutdatedSwapchainException", "d1/d3e/group__vkSwapchain.html#d0/d84/structvk_1_1OutdatedSwapchainException", null ],
      [ "PhysicalDevice", "d1/d93/group__vkDevice.html#d9/da9/classvk_1_1PhysicalDevice", "d1/d93/group__vkDevice_d9/da9/classvk_1_1PhysicalDevice" ],
      [ "Queue", "dd/d98/group__vkQueue.html#df/d93/classvk_1_1Queue", "dd/d98/group__vkQueue_df/d93/classvk_1_1Queue" ],
      [ "QueueHint", "dd/d98/group__vkQueue.html#dd/df0/structvk_1_1QueueHint", null ],
      [ "QueuePool", "dd/d98/group__vkQueue.html#d5/d2a/classvk_1_1QueuePool", "dd/d98/group__vkQueue_d5/d2a/classvk_1_1QueuePool" ],
      [ "QueuePoolLayout", "dd/d98/group__vkQueue.html#df/d15/classvk_1_1QueuePoolLayout", "dd/d98/group__vkQueue_df/d15/classvk_1_1QueuePoolLayout" ],
      [ "RenderPass", "d6/d77/classvk_1_1RenderPass.html", "d6/d77/classvk_1_1RenderPass" ],
      [ "RenderPipeline", "dc/d2d/classvk_1_1RenderPipeline.html", "dc/d2d/classvk_1_1RenderPipeline" ],
      [ "Semaphore", "d4/d30/classvk_1_1Semaphore.html", null ],
      [ "ShaderCompiled", "d7/df0/classvk_1_1ShaderCompiled.html", null ],
      [ "StorageBuffer", "d8/d3e/classvk_1_1StorageBuffer.html", null ],
      [ "SurfaceMinimizedException", "d1/d93/group__vkDevice.html#d0/def/structvk_1_1SurfaceMinimizedException", null ],
      [ "Swapchain", "d1/d3e/group__vkSwapchain.html#db/de5/classvk_1_1Swapchain", "d1/d3e/group__vkSwapchain_db/de5/classvk_1_1Swapchain" ],
      [ "SwapchainCallback", "d9/da8/structvk_1_1SwapchainCallback.html", null ],
      [ "SwapchainImage", "d1/d3e/group__vkSwapchain.html#db/d98/classvk_1_1SwapchainImage", "d1/d3e/group__vkSwapchain_db/d98/classvk_1_1SwapchainImage" ],
      [ "SyncLine", "dd/da8/structvk_1_1SyncLine.html", null ],
      [ "SyncPoint", "d9/d7f/structvk_1_1SyncPoint.html", null ],
      [ "TextureSubLayers", "d5/df6/namespacevk.html#d6/de8/structvk_1_1TextureSubLayers", null ],
      [ "TextureSubRegion", "d5/df6/namespacevk.html#d9/d92/structvk_1_1TextureSubRegion", null ],
      [ "TimelineSemaphore", "dd/d6e/classvk_1_1TimelineSemaphore.html", null ],
      [ "UniformBuffer", "d1/df3/classvk_1_1UniformBuffer.html", null ],
      [ "VertexAttribute", "dc/d1e/classvk_1_1VertexAttribute.html", null ],
      [ "VertexBuffer", "dc/d13/classvk_1_1VertexBuffer.html", null ]
    ] ],
    [ "_Glyph", "dc/dea/struct__Glyph.html", null ],
    [ "_KeyCallback", "d5/d71/struct__KeyCallback.html", null ],
    [ "_KeyEvent", "d1/df4/struct__KeyEvent.html", null ],
    [ "_state", "df/dab/struct__state.html", null ],
    [ "_Thread", "da/d67/struct__Thread.html", null ],
    [ "_WindowCallback", "d6/d11/struct__WindowCallback.html", null ],
    [ "CharFlags", "da/d68/structCharFlags.html", null ],
    [ "ConvertedIterator", "d9/dd3/classConvertedIterator.html", null ],
    [ "CView", "db/d5a/classCView.html", null ],
    [ "Flags", "da/dcc/classFlags.html", null ],
    [ "Flags< BufferUseType >", "d3/dd0/group__vkBufferEnum.html#dd/d0c/classFlags_3_01BufferUseType_01_4", null ],
    [ "Flags< ColorComponents >", "dc/dc1/group__vkPipelineEnum.html#dc/d30/classFlags_3_01ColorComponents_01_4", null ],
    [ "Flags< CommendBufferUsage >", "de/ded/group__vkCommendEnum.html#da/d10/classFlags_3_01CommendBufferUsage_01_4", null ],
    [ "Flags< CommendPoolType >", "de/ded/group__vkCommendEnum.html#d1/d07/classFlags_3_01CommendPoolType_01_4", null ],
    [ "Flags< CullMode >", "dc/dc1/group__vkPipelineEnum.html#d3/d12/classFlags_3_01CullMode_01_4", null ],
    [ "Flags< DescriptorPoolType >", "df/d47/group__vkDescriptorEnum.html#de/d9b/classFlags_3_01DescriptorPoolType_01_4", null ],
    [ "Flags< ImageUseType >", "d6/d8c/group__vkImageEnum.html#dd/d3d/classFlags_3_01ImageUseType_01_4", null ],
    [ "Flags< MemoryAccess >", "d4/d07/group__vkMemoryEnum.html#d5/dc9/classFlags_3_01MemoryAccess_01_4", null ],
    [ "Flags< MemoryFeature >", "d4/d07/group__vkMemoryEnum.html#d2/d6a/classFlags_3_01MemoryFeature_01_4", null ],
    [ "Flags< PipelineStage >", "dc/dc1/group__vkPipelineEnum.html#d7/de0/classFlags_3_01PipelineStage_01_4", null ],
    [ "Flags< QueueType >", "d6/d73/group__vkQueueEnum.html#d9/d5e/classFlags_3_01QueueType_01_4", null ],
    [ "Flags< SampleCount >", "d6/d8c/group__vkImageEnum.html#de/dae/classFlags_3_01SampleCount_01_4", null ],
    [ "Flags< ShaderType >", "de/d2c/group__vkShaderEnum.html#d7/d5d/classFlags_3_01ShaderType_01_4", null ],
    [ "Flags< TextureAspect >", "d6/d8c/group__vkImageEnum.html#dc/d09/classFlags_3_01TextureAspect_01_4", null ],
    [ "Flags< TextureFeature >", "d6/d8c/group__vkImageEnum.html#d4/d89/classFlags_3_01TextureFeature_01_4", null ],
    [ "ImageContainer", "da/dc9/structImageContainer.html", null ],
    [ "iterator_return", "d0/d49/structiterator__return.html", null ],
    [ "Log", "d0/d77/classLog.html", null ],
    [ "MemoryResource", "d5/d6a/classMemoryResource.html", null ],
    [ "MultiCharState", "d7/d7c/structMultiCharState.html", null ],
    [ "MultilineString", "de/d98/classMultilineString.html", null ],
    [ "MultiStream", "d1/dd1/classMultiStream.html", "d1/dd1/classMultiStream" ],
    [ "RollingAverage", "d0/d33/classRollingAverage.html", null ],
    [ "StringBox", "df/df4/classStringBox.html", null ],
    [ "Swapper", "d3/d0f/classSwapper.html", null ],
    [ "View", "d7/d9f/classView.html", null ],
    [ "VkAttachmentDescription", "d9/de5/classVkAttachmentDescription.html", null ],
    [ "VkPipelineColorBlendAttachmentState", "d9/dcc/classVkPipelineColorBlendAttachmentState.html", null ],
    [ "VkPipelineDepthStencilStateCreateInfo", "d7/da7/classVkPipelineDepthStencilStateCreateInfo.html", null ],
    [ "VkPipelineShaderStageCreateInfo", "de/d66/classVkPipelineShaderStageCreateInfo.html", null ],
    [ "VkPushConstantRange", "d1/dd4/classVkPushConstantRange.html", null ],
    [ "VkSubpassDependency", "d0/dee/classVkSubpassDependency.html", null ]
];